language: android

android:
  components:
    - android-21
    - extra-android-m2repository

env:
  -  TERM=dumb

# Build Tools Install (21.1.2)
before_script:
  - echo yes | android update sdk --all --filter build-tools-21.1.2 --no-ui --force > /dev/null

script:
  - ./gradlew assembleDebug